### ISSUE TITLE
'freeze_backbone' is not defined

### ISSUE THREAD

**Issue by IzzaRabbani** [yassouali/pytorch-segmentation#114]
while using deeplabv3, getting error that freeze_backbone is not defined

**Comment by yassouali** [comment]
just fixed this in the mast commit, simply add `freeze_backbone=False` in the arguments

**Comment by IzzaRabbani** [comment]
[
![Screenshot from 2021-05-20 15-43-20](https://user-images.githubusercontent.com/73467658/118965472-2b672880-b982-11eb-8821-10fef028d3aa.png)
](url)

**Comment by yassouali** [comment]
you'll just need to add the input argument:

![image](https://user-images.githubusercontent.com/45082182/118965882-6e68d200-b969-11eb-8807-51dd785d67e4.png)

**Comment by IzzaRabbani** [comment]
Thank you
