### ISSUE TITLE
页面文件太小，无法完成操作

### ISSUE THREAD

**Issue by jhon353** [yassouali/pytorch-segmentation#118]
OSError: [WinError 1455] 页面文件太小，无法完成操作。 Error loading "F:\anaconda3\envs\pytorch\lib\site-packages\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.

**Comment by yassouali** [comment]
Hi @jhon353 

Sorry but this issue is probably related to your environment and not this repo. I think you can find a quick fix by some google or github searches. For example this one: https://github.com/pytorch/pytorch/issues/35803.


Good luck.
