### ISSUE TITLE
Binary segmentation on a custom dataset

### ISSUE THREAD

**Issue by Avigyan2001** [yassouali/pytorch-segmentation#122]
I want to perform a binary segmentation on a custom dataset which contains images in 4 channels i.e. RGB-NIR. 
If someone could guide me as to how do I use this repo to train any model like psp-net or deeplabv3+ on my dataset.
Where do I have to make all the changes in the code to perform the training and evaluation?
I am lost and a help would be very much appreciated.

**Comment by yassouali** [comment]
Hi, @Avigyan2001 

You only need to right a new dataloader (can be based on the provided ones) to load your training data, and then simply set the input_channels in the config file to 3, and you can then start training.

example:
```bash
    "arch": {
        "type": "PSPNet",
        "args": {
            "backbone": "resnet50",
            "freeze_bn": false,
            "freeze_backbone": false,
            "in_channels": 3,
        }
    },
```
