### ISSUE TITLE
How to write SegNet Deep Learning code dealing with ".tiff" images?

### ISSUE THREAD

**Issue by JenniferYingyiWu2020** [yassouali/pytorch-segmentation#124]
Hi,
        I have read the supervised machine learning on the page of "https://rasterframes.io/supervised-learning.html", now I would like to implement SegNet (Semantic Segmentation) Deep Learning which is integrated with RasterFrames.
        However, I am so confused about how to write SegNet Deep Learning code dealing with ".tiff" images? So, would you pls help to give me some suggestions? Many Thanks!

**Comment by yassouali** [comment]
hi @JenniferYingyiWu2020 

the provided dataloader already work with .tiff image (since PIL already load such images without any overhead); so you can simply modify one of the dataloader (see closed issues for more details) for your data.


Good luck.
