### ISSUE TITLE
inference

### ISSUE THREAD

**Issue by Dejavusd** [yassouali/pytorch-segmentation#129]
An error is reported when predicting the picture:
RuntimeError: CUDA out of memory. Tried to allocate 662.00 MiB (GPU 0; 4.00 GiB total capacity; 2.09 GiB already allocated; 311.14 MiB free; 2.27 GiB reserved in total by 

> {
    "name": "deeplabv3_plus",
    "n_gpu": 1,
    "use_synch_bn": false,

    "arch": {
        "type": "DeepLab",
        "args": {
            "backbone": "Xception",
            "freeze_bn": false,
            "freeze_backbone": false
        }
    },

    "train_loader": {
        "type": "CityScapes",
        "args":{
            "data_dir": "data/cityscapes",
            "batch_size": 4,
            "base_size": 400,
            "crop_size": 225,
            "augment": true,
            "shuffle": true,
            "scale": true,
            "flip": true,
            "rotate": true,
            "blur": false,
            "split": "train",
            "num_workers": 8
        }
    },

    "val_loader": {
        "type": "CityScapes",
        "args":{
            "data_dir": "data/cityscapes",
            "batch_size": 4,
            "crop_size": 480,
            "val": true,
            "split": "val",
            "num_workers": 4
        }
    },

    "optimizer": {
        "type": "SGD",
        "differential_lr": true,
        "args":{
            "lr": 0.01,
            "weight_decay": 1e-4,
            "momentum": 0.9
        }
    },

    "loss": "CrossEntropyLoss2d",
    "ignore_index": 255,
    "lr_scheduler": {
        "type": "Poly",
        "args": {}
    },

    "trainer": {
        "epochs": 80,
        "save_dir": "saved/",
        "save_period": 10,
  
        "monitor": "max Mean_IoU",
        "early_stop": 10,
        
        "tensorboard": true,
        "log_dir": "saved/runs",
        "log_per_iter": 20,

        "val": true,
        "val_per_epochs": 10
    }
}

**Comment by yassouali** [comment]
Hi @Dejavusd 

In this case try reducing the image size of the batch size.
