### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by BFMM123456** [yassouali/pytorch-segmentation#130]
{
    "name": "PSPNet",
    "n_gpu": 1,
    "use_synch_bn": false,

    "arch": {
        "type": "PSPNet",
        "args": {
            "backbone": "resnet50",
            "freeze_bn": false,
            "freeze_backbone": false
        }
    },

    "train_loader": {
        "type": "cityscapes",
        "args":{
            "data_dir": "G:/7/pytorch-segmentation-master/data/cityscapes",
            "batch_size": 8,
            "base_size": 400,
            "crop_size": 380,
            "augment": true,
            "shuffle": true,
            "scale": true,
            "flip": true,
            "rotate": true,
            "blur": false,
            "split": "train_aug",
            "num_workers": 8
        }
    },

    "val_loader": {
        "type": "VOC",
        "args":{
            "data_dir": "G:/7/pytorch-segmentation-master/data/cityscapes",
            "batch_size": 8,
            "crop_size": 480,
            "val": true,
            "split": "val",
            "num_workers": 4
        }
    },

    "optimizer": {
        "type": "SGD",
        "differential_lr": true,
        "args":{
            "lr": 0.01,
            "weight_decay": 1e-4,
            "momentum": 0.9
        }
    },

    "loss": "CrossEntropyLoss2d",
    "ignore_index": 255,
    "lr_scheduler": {
        "type": "Poly",
        "args": {}
    },

    "trainer": {
        "epochs": 80,
        "save_dir": "saved/",
        "save_period": 10,
  
        "monitor": "max Mean_IoU",
        "early_stop": 10,
        
        "tensorboard": true,
        "log_dir": "saved/runs",
        "log_per_iter": 20,

        "val": true,
        "val_per_epochs": 5
    }
}

**Comment by mindmad** [comment]
Hi @BFMM123456,  have you fixed this issue. if possible can you share here how to fix it

**Comment by BFMM123456** [comment]
数据集名字写错了，所以没有找到，报错的。我把数据集名字按照__init__里面的改回来就好了
