### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by fika321** [yassouali/pytorch-segmentation#131]
Traceback (most recent call last):
  File "train.py", line 72, in <module>
    main(config, args.resume)
  File "train.py", line 32, in main
    train_loader = get_instance(dataloaders, 'train_loader', config)
  File "train.py", line 26, in get_instance
    return getattr(module, config[name]['type'])(*args, **config[name]['args'])
TypeError: 'module' object is not callable

**Comment by yassouali** [comment]
i think you just need to double check the name of the dataset you have in the config to match one of the class names in dataloaders/
