### ISSUE TITLE
How to modify pre-training weights

### ISSUE THREAD

**Issue by Atom0808** [yassouali/pytorch-segmentation#132]
I don’t want to use the automatically downloaded pre-training weights (renet 50). How can I modify the pre-training weights? Where in the script, I did not find a location where I can modify the path of the .pth file. I would appreciate it if you can reply.
<img width="259" alt="1111111" src="https://user-images.githubusercontent.com/75409500/147062749-79463dca-5d92-44a7-aa40-84ef0b2e4ade.png">

**Comment by Atom0808** [comment]
I also saw your answer, but I did not find the encoder in the definition of the model, thank you for your serious answer
<img width="577" alt="11111" src="https://user-images.githubusercontent.com/75409500/147095548-014e2bfe-f564-4dd9-9786-308d9ad23853.png">

**Comment by yassouali** [comment]
the encoder is defined here: https://github.com/yassouali/pytorch-segmentation/blob/master/models/resnet.py
