### ISSUE TITLE
Using Unet for training in Freiburg Forest dataset

### ISSUE THREAD

**Issue by deolipankaj** [yassouali/pytorch-segmentation#137]
Hi, 

Thank you for the awesome repo for segmentation. I was able to replicate training Unet for cityscapes dataset. However If i want to train the UNet on Freiburg Forest dataset, i am unable to understand how to modify the dataloader file. 

Can u give a suggestion or hint as to what can be done ?

Best Regards

**Comment by yassouali** [comment]
Hi @deolipankaj 

Sorry for the delayed response, you basically just need to write a dataclass that loads each image and its segmentation map, and then use this dataset to create you data loader that calls this dataset (you just need to follow the examples in [dataloader](https://github.com/yassouali/pytorch-segmentation/tree/master/dataloaders))

Best regards
