### ISSUE TITLE
Resnet model URLs inaccessible

### ISSUE THREAD

**Issue by scott-wade** [yassouali/pytorch-segmentation#142]
The URLs for resnet50, resnet101, and resnet152 are inaccessible. This causes a 403 error when creating models of these types. 
![image](https://user-images.githubusercontent.com/78106639/199032004-3d28e2c5-3234-447d-b6ff-480e01f26ba4.png)
![image](https://user-images.githubusercontent.com/78106639/199032082-d28eeb63-8653-4007-ae0f-59f521c749b5.png)

**Comment by yassouali** [comment]
hi @scott-wade 

You can find a mirror here: https://github.com/yassouali/pytorch-segmentation/releases
